src/main/java/com/github/luben/zstd/ZstdInputStream.java, src/main/java/com/github/luben/zstd/ZstdOutputStream.java, src/test/scala/Zstd.scala
The current In/OutputStream implementations fail to override read() and write(int), which leads to these methods being forwarded directly to the underlying stream, bypassing Zstd entirely.
This leads to corrupted files during output and mysterious errors during input.
One example of code using InputSteam.read() in the wild is Google ProtoBuffers' "parseDelimitedFrom(InputStream)" method, but there are probably others.
=> (Bugfix) Support OutputStream.write(int byte) / InputStream.read()

src/main/java/com/github/luben/zstd/Zstd.java, src/main/native/jni_zstd.c, src/test/scala/Perf.scala, src/test/scala/Zstd.scala
The details of this change are described in the issue #16 .
This adds overloads to `compress` and `decompress` that operate on `ByteBuffer`s instead of `byte[]`s.
=> Fix Issue #16: Implement support for directe ByteBuffers

src/main/java/com/github/luben/zstd/ZstdDirectBufferCompressingStream.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferDecompressingStream.java
I was reading a bit more about [how direct ByteBuffers are released](https://stackoverflow.com/questions/36077641/java-when-does-direct-buffer-released), and thought to help the GC a bit with explicitly clearing the field with the pointer to the buffer.
=> Release the ByteBuffer a bit more explicitly

README.md
I spotted couple typos in the README. Here are some edits.
Thank you so much for putting this together.
I'm using zstd-jni before some cpu-heavy encryption to reduce the cost. Of all the jvm compressors I benchmarked (also counting encryption time where size reduction matters), zstd-jni was the fastest by far. It's awesome, and you're awesome.
=> Readme touch ups.

CMakeLists.txt, src/main/native/CMakeLists.txt
This pull request adds CMake files that make cross compiling easier, since I couldn't make `sbt compile` work with my cross compiler environment (in my case Yocto).
Usage
```
mkdir builddir
cd builddir
cmake ..
make
```
I'm aware that a parallel build system to sbt is not an optimal solution, so I don't know if this pull request is appropriate. But at least it fixes my cross compiling issues :-)
=> Add CMake to support cross compiling.

src/main/java/com/github/luben/zstd/Zstd.java, src/main/java/com/github/luben/zstd/ZstdDictTrainer.java, src/main/native/jni_zdict.c, src/test/scala/ZstdDict.scala
Attempting to add ability to use native byte buffers for training as copying large arrays causes JVM to stall. 
My familiarity with JNI is low. Would appreciate assistance.
It looks like the tests are running but they never finish running into this non-stop error message:
Cover must have at least one input file
Cover must have at least one input file
Cover must have at least one input file
Cover must have at least one input file
Cover must have at least one input file
Cover must have at least one input file
=> Training with direct byte buffer samples

src/main/java/com/github/luben/zstd/util/Native.java
On Linux & Mac, tempLib.delete() will delete temp native library after it is loaded. deleteOnExit() is ineffective but left it just in case.
Neither works on Windows. More info here:
https://stackoverflow.com/questions/33226381/cannot-delete-a-temporary-file-when-it-is-used-to-load-a-system-library
https://stackoverflow.com/questions/453359/how-to-unload-library-dll-from-java-jvm
=> Clean up temporary native library on Linux. Does not work on Windows

src/main/native/dictBuilder/cover.c, src/test/scala/ZstdDict.scala
I have added a test that made the test hang before the change to the native code.
The modification of the cover.c code changes the abrupt return in the bad-case into just not storing the dict and returning through the same cleanup as the good case uses. The test then no longer gets stuck.
I hit this in production from trying to make a dict from too little entropy it seems.(?)
=> Release the mutex also when no dict results from analysis.

src/main/java/com/github/luben/zstd/ZstdOutputStream.java
This will fix both #83 and #119 . It guaranteed to close the opaque pointer to Zstd context object on close call and will set isClosed flag before cleaning the context from native code using freeCStream.
Hence this will prohibit the JVM crashes and Memory leaks. The finalize call will skip the close if the stream is already closed.
=> Guaranteed Zstd Context Clousure and No Operation allowed after Clousure

src/main/java/com/github/luben/zstd/ZstdInputStream.java, src/test/scala/Zstd.scala
Without this fix, the attached unit test goes into an infinite loop. This is because `readInternal` would return 0 [here](https://github.com/tgregg/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdInputStream.java#L152), causing it to forever satisfy the condition of the [while loop](https://github.com/tgregg/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdInputStream.java#L119) in `read` because additional bytes never become available in the underlying InputStream.
This is not a typical case, as continuous mode would typically be used when a different thread or process is producing the stream. Eventually the bytes that complete the frame will come available and the loop will break.
However, in exceptional conditions, those bytes may never arrive. For example, say …
=> Fix infinite loop in continuous mode when reading an incomplete frame.

build.sbt, src/main/native/jni_fast_zstd.c, src/main/native/jni_zdict.c
Looks like MSVC does not like it and returns C2036 error. Needed to
perform this change when integrating zstd into bazel to make it
compile under Windows:
https://github.com/bazelbuild/bazel/pull/11968/commits/02e0515d792efbd9d7cd168d1f23d246cd8b534a
See: https://github.com/bazelbuild/bazel/pull/11968
=> Remove pointer arithmetic

src/main/java/com/github/luben/zstd/BufferPool.java, src/main/java/com/github/luben/zstd/ZstdInputStream.java, src/main/java/com/github/luben/zstd/ZstdOutputStream.java, src/test/scala/Zstd.scala
I added a BufferPool class to allow the library to reuse internal buffers. I had noted that there were a decent amount of large allocations and some GC activity occurring. Since all of these buffers are the same size, it was an ideal candidate for buffer reuse. This should provide some relief in scenarios where maybe a ZstdOutputStream/ZstdInputStream is allocated once per file or connection or other resource in an application (specifically Kafka) and those resources are periodically recycled.
I did choose to remove the ability to pass in the byte[] into the ZstdInputStream, since in that case it would be unclear who owned that byte[]. Also in the discussion of https://github.com/luben/zstd-jni/issues/131 it was made clear that a reuse behavior was desired and could not use any non-Java …
=> Reuse internal buffers

src/main/java/com/github/luben/zstd/BufferPool.java, src/main/java/com/github/luben/zstd/RecyclingBufferPool.java, src/main/java/com/github/luben/zstd/Zstd.java, src/main/java/com/github/luben/zstd/ZstdInputStream.java, src/main/java/com/github/luben/zstd/ZstdOutputStream.java, src/test/scala/Zstd.scala
I added a new interface to represent a BufferPool. I added some constructor arguments to allow users to pass in their implementation (like Snappy does).
For kafka, it should be very simple to make a shim that wraps their BufferSupplier https://github.com/apache/kafka/blob/b6ce9d68627bda904924ba2dce5c334a2c615e18/clients/src/main/java/org/apache/kafka/common/record/BufferSupplier.java
That was one of the main reasons I chose to use ByteBuffer rather than byte[]. I do the same check to make sure the ByteBuffers are properly able to be used: https://github.com/apache/kafka/blob/b6ce9d68627bda904924ba2dce5c334a2c615e18/clients/src/main/java/org/apache/kafka/common/record/KafkaLZ4BlockInputStream.java#L80
=> Allow users to pass in a BufferPool implementation

src/main/java/com/github/luben/zstd/Zstd.java, src/main/native/jni_zstd.c
Continuation of #133
Methods operating on `byte[]` are much more useful when `offset` is paired with `limit`, this allows to constrict the frame length that ZSTD native will use when calculating the decompressed size
TODO: The official docs recommend moving towards `ZSTD_getFrameContentSize` as it differentiates between various reasons why the decompressed size may not be available, while current implementation flattens them into 0
=> Add `Zstd.decompressedSize(src, offset, limit)`

.github/actions/qemu-cross/action.yml, .github/actions/qemu-cross/build.sh, .github/actions/qemu-cross/docker.sh, .github/workflows/ci-qemu-cross.yml, src/test/scala/Zstd.scala
This PR adds support for building and testing zstd-jni under qemu s390x emulation.
The goal of this PR is to help catch any potential issues early on platforms not currently natively supported on GitHub Actions. I've been doing some work recently testing zstd-jni on s390x and thought it might be useful to contribute these changes.
The new action sets up qemu on the runner and runs a custom step that runs an s390x docker container under qemu which is used to build and test with sbt. It should be easy to add other platforms as well but I have not tried that.
Some tests needed to be disabled for 1.5.0. See comments in the changes to src/test/scala/Zstd.scala. Happy to provide more detail if needed.
Building and testing under qemu is slower than native so not sure if the action should be run …
=> Add a GitHub Action to build and test under qemu s390x emulation

src/main/java/com/github/luben/zstd/Zstd.java, src/main/java/com/github/luben/zstd/ZstdCompressCtx.java, src/main/java/com/github/luben/zstd/ZstdDictCompress.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferCompressingStream.java, src/main/java/com/github/luben/zstd/ZstdOutputStream.java, src/main/java/com/github/luben/zstd/ZstdOutputStreamNoFinalizer.java, src/main/native/jni_zstd.c, src/test/scala/Zstd.scala
Introduces `Zstd.defaultCompressionLevel()` in favour of hard-coding the value 3 in several places.
=> Expose the default compression level

.github/actions/qemu-cross/build.sh, src/test/scala/Zstd.scala
Remove the tag on some tests that was added for
https://github.com/facebook/zstd/issues/2736 on big endian platforms now
that the issue is resolved in zstd 1.5.1.
Update CI so that all tests are run on s390x.
=> No longer skip tests on s390x platform since resolved with zstd 1.5.1

build.sbt, make_so.sh
The changes were tested on a LoongArch architecture Loongson-3A5000 processor (LoongArch is a new RISC ISA, which is a bit like MIPS or RISC-V).
=> Support LoongArch64

build.sbt, src/main/java/com/github/luben/zstd/ZstdDirectBufferCompressingStream.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferCompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferDecompressingStream.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferDecompressingStreamNoFinalizer.java, src/main/native/jni_directbuffercompress_zstd.c, src/main/native/jni_directbufferdecompress_zstd.c
Following the pattern set by ZstdInputStreamNoFinalizer and ZstdOutputStreamNoFinalizer, add NoFinalizer variants for the direct buffer compressing and decompressing streams. The original classes with finalizers are reimplemented as simple wrappers over the NoFinalizer variants.
https://github.com/luben/zstd-jni/issues/83
=> Add NoFinalizer variants for the direct buffer streams.

src/main/native/jni_directbuffercompress_zstd.c, src/main/native/jni_fast_zstd.c, src/main/native/jni_zstd.c
The ZSTD_ErrorCode enum (ZSTD_error_*) contains small integers. The normal ZSTD convention for returning errors is to return large size_t values. Therefore, for the cases fixed in this commit, the enum values need to be transformed, so the caller can recognize them as errors.
=> Fix some error return codes.

src/main/java/com/github/luben/zstd/EndDirective.java, src/main/java/com/github/luben/zstd/ZstdCompressCtx.java, src/main/java/com/github/luben/zstd/ZstdDecompressCtx.java, src/main/native/jni_fast_zstd.c, src/test/scala/Zstd.scala
The goal of this change is to enable the highest-performance (de)compression of streams. `ZSTD_compressStream2` and `ZSTD_decompressStream` are exposed on `ZstdCompressCtx` and `ZstdDecompressCtx` respectively. They work in terms of direct `ByteBuffer`s and allow non-blocking, incremental handling of streams. The new `reset()` methods on `ZstdCompressCtx` and `ZstdDecompressCtx` allow reusing contexts, avoiding unnecessary allocations and deallocations.
=> Add methods for streaming (de)compression of direct ByteBuffers.

src/main/native/jni_inputstream_zstd.c, src/main/native/jni_zdict.c, src/main/native/jni_zstd.c
With `-Wall` I am getting two categories of warnings: unused variable `clazz` and uninitialized variable `size`.
I would like to get rid of all warnings.
=> Suppress warnings

src/main/java/com/github/luben/zstd/Zstd.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferCompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferDecompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdInputStream.java, src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdOutputStream.java, src/main/java/com/github/luben/zstd/ZstdOutputStreamNoFinalizer.java
Initially we were throwing IOException for most of the errors. This does
no make it easy to tell if the problems is with the Zstd encoding or
with the underlying IO.
=> Throw ZstdException when the error is coming from Zstd

src/main/java/com/github/luben/zstd/ZstdDirectBufferCompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferDecompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdIOException.java, src/main/java/com/github/luben/zstd/ZstdInputStream.java, src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdOutputStream.java, src/main/java/com/github/luben/zstd/ZstdOutputStreamNoFinalizer.java
So that we don't break backward compatibility - ZstdIOException is
subclass of the IOException so signatures don't have to be changed.
=> Fix exceptions

build.sbt, src/main/java/com/github/luben/zstd/BaseZstdBufferDecompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdBufferDecompressingStream.java, src/main/java/com/github/luben/zstd/ZstdBufferDecompressingStreamNoFinalizer.java, src/main/native/jni_bufferdecompress_zstd.c, src/main/native/jni_directbufferdecompress_zstd.c, src/test/scala/Zstd.scala
**Motivation**
At Apache Kafka, [we always have the entire compression buffer](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/compress/ZstdFactory.java#L67) before we send it to Zstd to decompress. Hence, we don't need a stream to provide the buffer containing compressed data to Zstd. There is no interface in Zstd-JNI which allows to submit a buffer (containing compressed data) and return an InputStream containing uncompressed data.
**Changes**
1. Add a new interface `ZstdBufferDecompressingStreamNoFinalizer` which is similar to existing `ZstdDirectBufferDecompressingStreamNoFinalizer`, except, it works with heap buffers.
2. Refactor to extract out a common base class from the two classes above.
**Testing**
Added tests for the new interface.
=> Add ZstdBufferDecompressingStreamNoFinalizer

build.sbt
The javac --release is set to build for a Java version >= 6. So the OSGi declararation must also explicit set this version to not depend on the version of the JDK it is built with.
=> Set explicit Java version requirement for OSGi

src/main/java/com/github/luben/zstd/Zstd.java, src/main/java/com/github/luben/zstd/ZstdDictCompress.java, src/main/java/com/github/luben/zstd/ZstdDictDecompress.java, src/main/native/jni_fast_zstd.c, src/main/native/jni_zstd.c, src/test/scala/ZstdDict.scala
This avoid the critical region otherwise required on the byte array.
=> Added support for initialising a "dict" from a direct ByteBuffer.

src/main/java/com/github/luben/zstd/BaseZstdBufferDecompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdBufferDecompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdDirectBufferDecompressingStreamNoFinalizer.java, src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java, src/test/scala/Zstd.scala
resolves https://github.com/luben/zstd-jni/issues/252
At https://github.com/luben/zstd-jni/blob/master/src/main/java/com/github/luben/zstd/ZstdBufferDecompressingStreamNoFinalizer.java#L47-L48 extractArray() ensures that the buffer.arrayOffset() != 0. However, that is not a strict requirement for ZstdBufferDecompressingStream since it works with the case [1] where ByteBuffer may have a non-zero position.
- Remove the constraints that ensure that source & destination buffer have position at 0.
- Added some documentation to the public methods.
- Modified existing unit tests to include cases where the source and target buffers don't have position starting from 0.
- `./sbt clean compile test` is successful
=> Relax the requirement for source and target ByteBuffer in ZstdBufferDecompressingStream

src/main/java/com/github/luben/zstd/Zstd.java, src/main/java/com/github/luben/zstd/ZstdInputStream.java, src/main/java/com/github/luben/zstd/ZstdInputStreamNoFinalizer.java, src/main/native/jni_zstd.c, src/test/scala/ZstdDict.scala
resolves #261.
Added setting `ZSTD_d_refMultipleDDicts` that enables support for multiple dictionary references in a decompression streaming context. With `refMultipleDDicts -> true`, zstd searches for a suitable dictionary by matching the dictionaryId in the frame among known dictionaries (loaded via `setDict`).
=> Add support for multiple dictionary references in streaming decompression

src/main/java/com/github/luben/zstd/ZstdBufferDecompressingStreamNoFinalizer.java, src/test/scala/Zstd.scala
The current implementation of ZstdBufferDecompressingStream fails with `com.github.luben.zstd.ZstdIOException: Unknown frame descriptor` when the interface is used with a ByteBuffer which is backed by an array which is shared with other ByteBuffers. This is a bug in the implementation where we assume that the ByteBuffer represents the view of the entire backing array.
Change the implementation to specifically use the array represented by the bytebuffer view instead of the entire backing array.
Added a test case which fails prior to the change and passes after it.
=> Fix bug in ZstdBufferDecompressingStream when array backing ByteBuffer is shared

build.sbt
Hi,
Can I have a discussion about the supported jdk versions of zstd-jni?
In the `build.sbt`, jdk1.6 is still supported:
```
javacOptions ++= Seq("--release", "6", "-Xlint:unchecked")
...
doc / javacOptions := Seq("--release", "6")
...
OsgiKeys.requireCapability := "osgi.ee;filter:=\"(&(osgi.ee=JavaSE)(version>=1.6))\""
```
I'm not sure if this is necessary, but seems this blocks the usage of zstd-jni in jdk 17/21 and later?
```
$ javac -version
javac 17.0.2
hamlin@hamlin:~/workspace/tools$ javac --release 6 Test.java
error: release version 6 not supported
Usage: javac <options> <source files>
use --help for a list of possible options
```
Do we have a plan to migrate the supportted jdk version from 1.6 to 1.8? If positive, this is the pr to do it.
Thanks!
=> Migrate supported java version from 1.6 to 1.8

README.md, build.sbt, make_so_cross.sh
Hi,
Can you take a look at this patch which try to bring basic riscv64 support to zstd-jni?
This patch is based on pr #281 , and pr #281 .
Thanks!
I have run the test via QEMU by following command:
```
CC=riscv64-linux-gnu-gcc ./sbt -java-home ~/jdk/build/linux-riscv64-server-release/images/jdk/ testOnly
```
There are lots of output, seems there is no error, and the bottom lines of output are:
```
[info] Total number of tests run: 151
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 151, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```
=> Enable basic support for riscv64

make_so_cross.sh
Hi,
Can you review this simple change?
It removes the `-march` argument when cross-compile riscv in make_so_cross.sh. This is to let the compiler to pick up the default arch, to enable most compatability on different hardwares.
Thanks!
=> Remove -march for riscv

.github/workflows/ci.yml
https://github.com/actions/setup-java/blob/main/README.md
=> setup-java v4

src/main/java/com/github/luben/zstd/ZstdDictCompress.java, src/main/java/com/github/luben/zstd/ZstdDictDecompress.java, src/main/native/jni_fast_zstd.c, src/test/scala/ZstdDict.scala
that allows the byReference semantics for the provided byte buffer: If you set this to true, you avoid the copying of the dict data into a natively malloc'ed buffer, but then also have to promise that the byte buffer will not be modified before the CTX has been closed.
=> Add new constructor to ZstdDictCompress and ZstdDictDecompress

src/main/java/com/github/luben/zstd/ZstdDictCompress.java, src/main/java/com/github/luben/zstd/ZstdDictDecompress.java
Even when using a by-reference buffer, the dict struct itself is malloc'ed and thus needs freeing to not leak memory.
The leak is fairly slow, as it leaks the size of the `struct ZSTD_CDict_s` (and  `ZSTD_DDict_s` for decompress) on every use, which takes quite a few rounds to become visible as an increase in overall process size.
The issue affects exclusively uses of the (new in v1.5.6-2) `getByReferenceBuffer` variants.
I would like to request a version bump and a new published build to allow using this downstream.
Fixes: https://github.com/luben/zstd-jni/issues/310
=> Fix missing native free of Dict

src/main/java/com/github/luben/zstd/Objects.java, src/main/java/com/github/luben/zstd/ZstdCompressCtx.java, src/main/java/com/github/luben/zstd/ZstdDecompressCtx.java
Sorry, somehow I closed my previous PR when I tried to force push my new version.
So, checking the offset/size is easy in the Java side, if it's allowed to raise the Java language version to 11 - the Objects.checkFromIndexSize introduced after 8, so otherwise the compiler complains
=> Show better error message, when the src/dst offset is negative

src/main/java/com/github/luben/zstd/Zstd.java, src/main/native/dictBuilder/zdict.c, src/main/native/jni_zdict.c, src/main/native/zdict.h
The compression improves when the level for the training is close to the level for the compression step. 
(100% Compatible for the public API.)
=> Allow including compression level when training a dictionary

src/main/java/com/github/luben/zstd/ZstdDictTrainer.java
@luben Sorry, not sure if I should have added you as a reviewer somehow
=> Add support for compression level in ZstdDictTrainer

src/main/java/com/github/luben/zstd/Zstd.java, src/main/java/com/github/luben/zstd/ZstdDecompressCtx.java, src/main/native/jni_fast_zstd.c, src/test/scala/Zstd.scala
HBase uses zstd-jni for one implemention of its ZStandard support. I've been working on improving ZStandard decompression performance in HBase. My goal is to avoid copying data any more than absolutely necessary. In some situations, we have our compressed data in a byte array, and need to decompress into a direct ByteBuffer, or vice versa. This is not currently possible without an extra copy. In this PR, I expose the methods to accomplish this. My hope is that this PR gets accepted, and HBase can use the next version of zstd-jni to get a little performance boost.
=> Support decompression from byte array to ByteBuffer and vice-versa

src/main/native/jni_zstd.c, src/test/scala/Zstd.scala
Fix segmentation fault when calling ZstdOutputStream#setDict(ZstdDictCompress) with null
For example:
```
💣 Program crashed: Bad pointer dereference at 0x0000000000000000
Thread 73 "Java: pool-18-thread-15-ScalaTest-running-ZstdSpec" crashed:
0 0x0000000103077460 AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<1097844ull, G1BarrierSet>, (AccessInternal::BarrierType)2, 1097844ull>::oop_access_barrier(void*) + 8 in libjvm.dylib
1 0x00000001031c495c jni_GetObjectClass + 184 in libjvm.dylib
2 0x000000012800bbfc
3 0x0000000128006ab0
4 0x0000000128006ee0
5 0x0000000128006ee0
6 0x0000000128006ee0
7 0x0000000128006fc8
8 0x0000000128006ee0
9 0x0000000128006ee0
10 0x0000000128006ee0
11 0x0000000128006ee0
12 0x0000000128006fc8
13 0x0000000128006fc8
14 0x0000000128006ee0
15 …
```
=> Fix segmentation fault when calling ZstdOutputStream#setDict(ZstdDictCompress) with null

src/main/native/jni_zdict.c, src/main/native/jni_zstd.c, src/test/scala/Zstd.scala
Fix segmentation faults in:
- Java_com_github_luben_zstd_Zstd_trainFromBuffer0
- Java_com_github_luben_zstd_Zstd_loadDictDecompress
- Java_com_github_luben_zstd_Zstd_loadFastDictDecompress
- Java_com_github_luben_zstd_Zstd_loadDictCompress
=> Fix segmentation faults

src/main/java/com/github/luben/zstd/ZstdCompressCtx.java, src/main/java/com/github/luben/zstd/ZstdDecompressCtx.java, src/test/scala/Zstd.scala
"result & 0xFF" always yields a positive number, but ZstdErrorCode needs negative number.
=> fix: compress & decompress DirectByteBufferStream error is always ZSTD_error_no_error
